### ISSUE TITLE
Send to influxDB via a proxy

### ISSUE THREAD

**Issue by neubauerf** [niwo/cloudstack_stats#1]
We are using influxcloud (hosted influxdb) and no vm's are directly connected to the internet. Our telegraf agent and python scripts can all send data via a proxy server to the destination influxdb server. Is it possible to add this functionality? 

Great project btw!

**Comment by niwo** [comment]
Net::HTTP will automatically create a proxy from the http_proxy environment variable if it is present.

So you can use

`ENV['http_proxy'] = 'http://172.16.3.160:4226' # your http://address:port here` and Net::HTTP will use it for all requests by default.

Pass nil for the proxy address to disable default http_proxy.
